services:
  pgdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    # ports:
      # - 5432:5432
  pgdb_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pudovninmihail@gmail.com
      - POSTGRES_USER=hello_django
      - PGADMIN_DEFAULT_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 5432:80
  sudoku_solver:
    build: .
    depends_on:
      - pgdb
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_USER=hello_django
      - DB_PASSWORD=hello_django
      - DB_NAME=sudoku
    ports:
      - 8080:8080
    # volumes:
    #   - .:/app
    # command: ./sudoku_solver

volumes:
  postgres_data: